#!/usr/bin/env python

from termcolors import *
import sys

tc = []
for n in xrange(len(tf)): tc.append((tf[n], tfl[n]))

for b in tb:
	for c, lc in tc:
		sys.stdout.write("%s %s " % \
			(globals()[b](globals()[c]('XXXXX')), globals()[b](globals()[lc]('OOOOO'))))
	print('\n')

